### PR TITLE
Add `range` APIs

### LINKED ISSUE #17: Add `range` APIs
To mirror `BTreeSet`'s [`range`](https://doc.rust-lang.org/stable/std/collections/struct.BTreeSet.html#method.range), and `BTreeMap`'s [`range`](https://doc.rust-lang.org/std/collections/btree_map/struct.BTreeMap.html#method.range)/[`range_mut`](https://doc.rust-lang.org/std/collections/btree_map/struct.BTreeMap.html#method.range_mut).

To help navigate the codebase:

* `src/tree/tree.rs` is where the majority of logic is implemented, both sets and maps are public wrappers around this tree. Since v2.0, this module is internal-only (not part of crate's public API). So you're free to make any changes necessary to support the `range` APIs. Current iterator implementations live in `src/tree/iter.rs`.

* Return types like [`Range`](https://doc.rust-lang.org/std/collections/btree_map/struct.Range.html) should be added to `src/set_types.rs` and `src/map_types.rs`.

### PR DESCRIPTION
**Pull request by TheDoctor314**
Fixes #17.

Rough implementation. Iterator is not *really* lazy since we look for the node indexes initially.

### CODE REVIEW

**Review by tnballo — CHANGES_REQUESTED** [review]
This looks great! I really like your design, it's very clean. IMO correct functionality is the majority of value, lazy optimization can always be added later while maintaining the same interface.

Regarding the lifetime problem: oh nooooo, when opening #17 I totally forgot that safe mutable iterators are **extremely difficult** in Rust (see [this post](https://users.rust-lang.org/t/how-to-implement-a-safe-mutable-iterator-for-vec-t/33297) for an example, even though the solution doesn't apply here AFAIK).

So you've hit the hardest problem in this whole codebase, unfortunately! Maybe even one of the harder problems in Rust programming. Sorry for the frustration that may have caused, `range_mut` is actually a big ask.

Now that my memory is jogged, here's the trick/hack this library uses to support regular (non-range) `iter_mut` for `SgMap` safely:

* We can sidestep the insane problem by creating a "pass-through" to the `iter_mut` method on `tinyvec::ArrayVec` (our arena). Throwing the work to a "deeper" type is a generally applicable way to handle this particular problem.

* Because we get a mutable reference, we can actually do [arbitrary] mutation internally when someone calls our `iter_mut`.

* So the trick is that the tree's `IterMut` struct (imported as `TreeIterMut` in `map_types.rs`), on creation, [sorts the arena `ArrayVec`](https://github.com/tnballo/scapegoat/blob/d5f1f6b2ccb401d09aad035c8fe8cca35797b4ae/src/tree/iter.rs#L96) to force the nodes to appear in ascending order, packed to the front of storage.

* Then, since the arena is now sorted, we leverage `ArrayVec`'s `iter_mut` [like so](https://github.com/tnballo/scapegoat/blob/d5f1f6b2ccb401d09aad035c8fe8cca35797b4ae/src/tree/iter.rs#L107).

Non-mutable iterators don't do this expensive arena sorting, because they don't need to in order to be safe and usable. So, with all that out of the way, here's what I'm thinking for this PR:

* Keep `Range` as is, using the nice `range_search` function you've added.
* Have `RangeMut` be a wrapper for the tree's `IterMut` explained above, re-using the [hacky but working] existing logic for safe mutable iteration. Something like:

```rust
pub struct RangeMut<'a, K: Ord + Default, V: Default, const N: usize> {
    pub(crate) inner: TreeIterMut<'a, K, V, N>,
}
```

That does mean `RangeMut`'s iterator logic will need to "run" `TreeIterMut` to *start* of the range in the constructor and "stop" potentially early in `next`, before the *end* of the range.

Hope that makes sense, it's a really tough thing to deal with. Thank you for your work on this! :thumbsup:

**Comment by TheDoctor314** [comment]
That does make sense. Implementing `Iterator` would be easy, but what about `DoubleEndedIterator`?

We could run `IterMut::next_back()` in `RangeMut::next_back()` but only if `IterMut` implements `DoubleEndedIterator`. It doesn't, so that's a breaking change.

Also if we are skipping elements, when we do find the element in range, we have already yielded that in the constructor, which will not be available when we call `next()`.

**Comment by tnballo** [comment]
Fortunately, `DoubleEndedIterator` is purely additive: it requires the type it's implemented on to already implement `Iterator`. So no conflict/break, just extra APIs. Adding it for the tree's `IterMut` entails additional complexity/work I didn't anticipate! 

One implementation could be `bst.sort_arena()` returns the arena index of the rightmost non-empty slot, and we "run" `ArrayVec`'s `iter_mut`'s `next_back` until that index (with `enumerate`) to initialize a `next_back` for `IterMut`.

But happy to accept this PR even without double-ended support for `IterMut` and `RangeMut`! Some of this library's iterators don't yet support the fancier iterator additions, like `ExactSizeIterator` and `DoubleEndedIterator`.

To avoid yielding the range's start element pre-maturely, I think [`peek()` can be used](https://doc.rust-lang.org/std/iter/struct.Peekable.html#method.peek) (available on all iterators) to check if it's the element we're looking for, and only call `next()` if not.

**Comment by TheDoctor314** [comment]
I might implement `DoubleEndedIterator` in a follow-up PR. For now, I hope this is satisfactory. Also way more generics than I initially thought there would be :smile: .

**Review by tnballo — APPROVED** [review]
Awesome, this is far beyond satisfactory! Nice use of `PhantomData` to help with the more flexible trait bounds. I haven't run into this language feature often, but I understand it better after seeing how you've used it here and why.

Yup, any future PR is always welcome if you find the time. These new `range` APIs are already a solid and significant addition. As before, I'll update the fuzzer, run it 24/7 for a couple days and check coverage, then release v2.2 on crates.io and update this thread.

PS - Wrote a [blog post](https://tiemoko.com/blog/diff-fuzz/) last week about fuzzing tools/research, specifically fuzzing this library, and had to include a shout out at the bottom of the post for your contributions! :blush:

**Comment by TheDoctor314** [comment]
> PS - Wrote a blog post last week about fuzzing tools/research, specifically fuzzing this library, and had to include a shout out at the bottom of the post for your contributions!

Wow that's thrilling! Thanks!

**Comment by tnballo** [comment]
No prob!

Fuzzing done, no issues, pushed v2.2 to crates.io. :tada:

Found a [slightly odd] way to simplify the generics a bit (updated `RangeMut<'_, T, R, K, V, N>` to `RangeMut<'_, K, V, N>`).

**Pull request merged**
